#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\AboutController::index
app_register:
  path: /register
  controller: App\Controller\RegistrationController::index
app_list:
  path: /list
  controller: App\Controller\ListController::index
app_upload:
  path: /upload
  controller: App\Controller\UploadController::index